## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file /home/josua/repos/uni/seminar/main.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_35 = Integer(35); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_30 = Integer(30); _sage_const_p1 = RealNumber('.1'); _sage_const_0p5 = RealNumber('0.5'); _sage_const_6 = Integer(6); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_67 = Integer(67); _sage_const_10 = Integer(10); _sage_const_16 = Integer(16)## This file (main.sagetex.sage) was *autogenerated* from main.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('main', version='2019/11/14 v3.4', version_check=True)
_st_.current_tex_line = _sage_const_35 
_st_.blockbegin()
try:
     t = var('t')
     LowerY = -_sage_const_3 
     UpperY = _sage_const_4 
     LowerX = -_sage_const_30 
     UpperX = _sage_const_30 
     step = _sage_const_p1 
     x_coords = [t for t in srange(LowerX,UpperX,step)]
     y_coords1 = [real_part(zeta(_sage_const_0p5  + t*I)).n(digits=_sage_const_6 ) for t in srange(LowerX,UpperX,step)]
     y_coords2 = [imag_part(zeta(_sage_const_0p5  + t*I)).n(digits=_sage_const_6 ) for t in srange(LowerX,UpperX,step)]
 
     output = r""
     output += r"\begin{tikzpicture}[scale=.7]"
     output += r"\begin{axis}[xmin=%f,xmax=%f,ymin= %f,ymax=%f, width=1.4\textwidth, height = 9cm, hide y axis, axis x line = middle, legend pos = north west]"%(LowerX,UpperX,LowerY, UpperY)
     output += r"\addplot[thin, blue, unbounded coords=jump] coordinates {"
     for i in range(_sage_const_0 ,len(x_coords)-_sage_const_1 ):
         if (y_coords1[i])<LowerY or (y_coords1[i])>UpperY:
             output += r"(%f , inf) "%(x_coords[i])
         else:
             output += r"(%f , %f) "%(x_coords[i],y_coords1[i])
     output += r"};"
     output += r"\addlegendentry{$\Re \zeta(\frac{1}{2} + ix)$}"
     output += r"\addplot[thin, red, unbounded coords=jump] coordinates {"
     for i in range(_sage_const_0 ,len(x_coords)-_sage_const_1 ):
         if (y_coords2[i])<LowerY or (y_coords2[i])>UpperY:
             output += r"(%f , inf) "%(x_coords[i])
         else:
             output += r"(%f , %f) "%(x_coords[i],y_coords2[i])
     output += r"};"
     output += r"\addlegendentry{$\Im \zeta(\frac{1}{2} + ix)$}"
     output += r"\end{axis}"
     output += r"\end{tikzpicture}"
except:
 _st_.goboom(_sage_const_67 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_10 
 _st_.inline(_sage_const_0 , output)
except:
 _st_.goboom(_sage_const_10 )
try:
 _st_.current_tex_line = _sage_const_16 
 _st_.inline(_sage_const_1 , output)
except:
 _st_.goboom(_sage_const_16 )
_st_.endofdoc()

