CC          = g++-mp-8
CCOPTS      = -g -O0 
OPTOPTS      = -O3
LIOPTS      = -lm

erstes_MAIN = erstes
erstes_INCLUDES = fcpp.hh

quadrat_MAIN = quadrat
quadrat_INCLUDES = fcpp.hh

absolut_MAIN = absolut
absolut_INCLUDES = fcpp.hh

fakultaet_MAIN = fakultaet
fakultaet_INCLUDES = fcpp.hh

fakultaetiter_MAIN = fakultaetiter
fakultaetiter_INCLUDES = fcpp.hh

fibonacci_MAIN = fibonacci
fibonacci_INCLUDES = fcpp.hh

fibiter_MAIN = fibiter
fibiter_INCLUDES = fcpp.hh

wechselgeld_MAIN = wechselgeld
wechselgeld_INCLUDES = fcpp.hh

ggT_MAIN = ggT
ggT_INCLUDES = fcpp.hh

newton_MAIN = newton
newton_INCLUDES = fcpp.hh

newtonwhile_MAIN = newtonwhile
newtonwhile_INCLUDES = fcpp.hh

enum_MAIN = enum
enum_INCLUDES = fcpp.hh

eratosthenes_MAIN = eratosthenes
eratosthenes_INCLUDES = fcpp.hh

ASCII_MAIN = ASCII
ASCII_INCLUDES = fcpp.hh

Cstring_MAIN = Cstring
Cstring_INCLUDES = fcpp.hh

CCstring_MAIN = CCstring
CCstring_INCLUDES = fcpp.hh

queens_MAIN = queens
queens_INCLUDES = fcpp.hh

Rational2_MAIN = Rational2
Rational2_INCLUDES = fcpp.hh

Complex2_MAIN = Complex2
Complex2_INCLUDES = fcpp.hh

konto1_MAIN = konto1
konto1_INCLUDES = fcpp.hh

wg-stack_MAIN = wg-stack
wg-stack_INCLUDES = fcpp.hh

stack1_MAIN = stack1
stack1_INCLUDES = fcpp.hh

montecarlo1_MAIN = montecarlo1
montecarlo1_INCLUDES = fcpp.hh

useintset_MAIN = useintset
useintset_INCLUDES = fcpp.hh intlist.cc intset.cc

Konto_MAIN = Konto
Konto_INCLUDES = fcpp.hh

MonteCarlo_MAIN = MonteCarlo
MonteCarlo_INCLUDES = fcpp.hh Zufall.cc Experiment.cc

Inkrementierer_MAIN = Inkrementierer
Inkrementierer_INCLUDES = fcpp.hh

UseRational_MAIN = UseRational
UseRational_INCLUDES = fcpp.hh Rational.cc Rational.hh

Turingmaschine_MAIN = Turingmaschine
Turingmaschine_INCLUDES = fcpp.hh Band.hh Band.cc Programm.hh Programm.cc TM.hh TM.cc

UseSimpleFloatArray_MAIN = UseSimpleFloatArray
UseSimpleFloatArray_INCLUDES = SimpleFloatArray.hh SimpleFloatArrayImp.cc SimpleFloatArrayIndex.cc SimpleFloatArrayCopyCons.cc SimpleFloatArrayAssign.cc

UseRationalOutput_MAIN = UseRationalOutput
UseRationalOutput_INCLUDES = fcpp.hh Rational.cc Rational.hh RationalOutput.cc

UsePolynomial_MAIN = UsePolynomial
UsePolynomial_INCLUDES = SimpleFloatArray.hh SimpleFloatArrayImp.cc SimpleFloatArrayIndex.cc SimpleFloatArrayCopyCons.cc SimpleFloatArrayAssign.cc Polynomial.hh PolynomialImp.cc PolynomialKons.cc PolynomialEqual.cc PolynomialEval.cc

UseCheckedSimpleFloatArray_MAIN = UseCheckedSimpleFloatArray
UseCheckedSimpleFloatArray_INCLUDES = SimpleFloatArray.hh SimpleFloatArrayImp.cc SimpleFloatArrayIndex.cc SimpleFloatArrayCopyCons.cc SimpleFloatArrayAssign.cc CheckedSimpleFloatArray.hh CheckedSimpleFloatArrayImp.cc

shape_MAIN = shape
shape_INCLUDES = 

Funktor_MAIN = Funktor
Funktor_INCLUDES = 

UseFloatArray_MAIN = UseFloatArray
UseFloatArray_INCLUDES = DFA.cc LFA.cc

Funktional-statisch_MAIN = Funktional-statisch
Funktional-statisch_INCLUDES =

UseSimpleArray_MAIN = UseSimpleArray
UseSimpleArray_INCLUDES = SimpleArray.hh SimpleArrayImp.cc

PtrTest_MAIN = PtrTest
PtrTest_INCLUDES = Ptr.hh

UseBubblesort_MAIN = UseBubblesort
UseBubblesort_INCLUDES = SimpleFloatArrayV.hh SimpleFloatArrayImp.cc SimpleFloatArrayIndex.cc SimpleFloatArrayCopyCons.cc SimpleFloatArrayAssign.cc SimpleArray.hh SimpleArrayImp.cc SimpleArrayCS.hh SimpleArrayCSImp.cc FloatArray.hh ListFloatArrayDerived.hh ListFloatArrayImp.cc timestamp.cc bubblesort_.cc Zufall.cc

UseListe_MAIN = UseListe
UseListe_INCLUDES = Liste.hh

UseDLL_MAIN = UseDLL
UseDLL_INCLUDES = DLL.hh

UseBoth_MAIN = UseBoth
UseBoth_INCLUDES = DLL.hh Array.hh

UseStack_MAIN = UseStack
UseStack_INCLUDES = DLL.hh

UseQueueSTL_MAIN = UseQueueSTL
UseQueueSTL_INCLUDES = DLL.hh

HuffmanSTL_MAIN = HuffmanSTL
HuffmanSTL_INCLUDES =

UseHeap_MAIN = UseHeap
UseHeap_INCLUDES = Heap.hh

UseSort_MAIN = UseSort
UseSort_INCLUDES = Bubblesort.cc Selectionsort.cc Insertionsort.cc Mergesort.cc Heapsort.cc Quicksort.cc Zufall.cc timestamp.cc

ABTree_MAIN = ab-tree
ABTree_INCLUDES = 

LSBeispiel_MAIN = LSBeispiel
LSBeispiel_INCLUDES = DLL.hh MinPriorityQueue.hh MinPriorityQueueImp.cc Queue.hh Wire.hh Circuit.hh Simulator.hh SimulatorImp.cc WireImp.cc Nand.hh NandImp.cc Terminal.hh TerminalImp.cc Fork.hh ForkImp.cc Analyzer.hh AnalyzerImp.cc Clock.hh ClockImp.cc

AdderBeispiel_MAIN = AdderBeispiel
AdderBeispiel_INCLUDES = DLL.hh MinPriorityQueue.hh MinPriorityQueueImp.cc Queue.hh Wire.hh Circuit.hh Simulator.hh SimulatorImp.cc WireImp.cc Nand.hh NandImp.cc Terminal.hh TerminalImp.cc Fork.hh ForkImp.cc Analyzer.hh AnalyzerImp.cc Clock.hh ClockImp.cc

EXECUTABLES = $(erstes_MAIN) $(quadrat_MAIN) $(absolut_MAIN) $(fakultaet_MAIN) $(fakultaetiter_MAIN) \
              $(fibonacci_MAIN) $(fibiter_MAIN) $(wechselgeld_MAIN) $(ggT_MAIN) $(newton_MAIN) \
              $(newtonwhile_MAIN) $(enum_MAIN) $(eratosthenes_MAIN) $(ASCII_MAIN) $(Cstring_MAIN) \
              $(CCstring_MAIN) $(queens_MAIN) $(Rational2_MAIN) $(Complex2_MAIN) $(konto1_MAIN) \
              $(wg-stack_MAIN) $(stack1_MAIN) $(montecarlo1_MAIN) $(useintset_MAIN) $(Konto_MAIN) \
              $(MonteCarlo_MAIN) $(Inkrementierer_MAIN) $(UseRational_MAIN) $(Turingmaschine_MAIN) \
              $(UseSimpleFloatArray_MAIN) $(UseRationalOutput_MAIN) $(UsePolynomial_MAIN) \
              $(UseCheckedSimpleFloatArray_MAIN) $(shape_MAIN) $(Funktor_MAIN) $(UseFloatArray_MAIN) \
              $(Funktional-statisch_MAIN) $(UseSimpleArray_MAIN) $(PtrTest_MAIN) $(UseBubblesort_MAIN) $(UseListe_MAIN) \
              $(UseDLL_MAIN) $(UseBoth_MAIN) $(UseStack_MAIN) $(UseQueueSTL_MAIN) $(HuffmanSTL_MAIN) $(UseHeap_MAIN) \
              $(UseSort_MAIN) $(ABTree_MAIN) $(LSBeispiel_MAIN) $(AdderBeispiel_MAIN) 

all : $(EXECUTABLES)

$(erstes_MAIN): $(erstes_MAIN).cc $(erstes_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(erstes_MAIN) $(erstes_MAIN).cc $(LIOPTS)

$(quadrat_MAIN): $(quadrat_MAIN).cc $(quadrat_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(quadrat_MAIN) $(quadrat_MAIN).cc $(LIOPTS)

$(absolut_MAIN): $(absolut_MAIN).cc $(absolut_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(absolut_MAIN) $(absolut_MAIN).cc $(LIOPTS)

$(fakultaet_MAIN): $(fakultaet_MAIN).cc $(fakultaet_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(fakultaet_MAIN) $(fakultaet_MAIN).cc $(LIOPTS)

$(fakultaetiter_MAIN): $(fakultaetiter_MAIN).cc $(fakultaetiter_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(fakultaetiter_MAIN) $(fakultaetiter_MAIN).cc $(LIOPTS)

$(fibonacci_MAIN): $(fibonacci_MAIN).cc $(fibonacci_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(fibonacci_MAIN) $(fibonacci_MAIN).cc $(LIOPTS)

$(fibiter_MAIN): $(fibiter_MAIN).cc $(fibiter_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(fibiter_MAIN) $(fibiter_MAIN).cc $(LIOPTS)

$(wechselgeld_MAIN): $(wechselgeld_MAIN).cc $(wechselgeld_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(wechselgeld_MAIN) $(wechselgeld_MAIN).cc $(LIOPTS)

$(ggT_MAIN): $(ggT_MAIN).cc $(ggT_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(ggT_MAIN) $(ggT_MAIN).cc $(LIOPTS)

$(newton_MAIN): $(newton_MAIN).cc $(newton_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(newton_MAIN) $(newton_MAIN).cc $(LIOPTS)

$(newtonwhile_MAIN): $(newtonwhile_MAIN).cc $(newtonwhile_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(newtonwhile_MAIN) $(newtonwhile_MAIN).cc $(LIOPTS)

$(enum_MAIN): $(enum_MAIN).cc $(enum_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(enum_MAIN) $(enum_MAIN).cc $(LIOPTS)

$(eratosthenes_MAIN): $(eratosthenes_MAIN).cc $(eratosthenes_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(eratosthenes_MAIN) $(eratosthenes_MAIN).cc $(LIOPTS)

$(ASCII_MAIN): $(ASCII_MAIN).cc $(ASCII_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(ASCII_MAIN) $(ASCII_MAIN).cc $(LIOPTS)

$(Cstring_MAIN): $(Cstring_MAIN).cc $(Cstring_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(Cstring_MAIN) $(Cstring_MAIN).cc $(LIOPTS)

$(CCstring_MAIN): $(CCstring_MAIN).cc $(CCstring_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(CCstring_MAIN) $(CCstring_MAIN).cc $(LIOPTS)

$(queens_MAIN): $(queens_MAIN).cc $(queens_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(queens_MAIN) $(queens_MAIN).cc $(LIOPTS)

$(Rational2_MAIN): $(Rational2_MAIN).cc $(Rational2_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(Rational2_MAIN) $(Rational2_MAIN).cc $(LIOPTS)

$(Complex2_MAIN): $(Complex2_MAIN).cc $(Complex2_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(Complex2_MAIN) $(Complex2_MAIN).cc $(LIOPTS)

$(konto1_MAIN): $(konto1_MAIN).cc $(konto1_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(konto1_MAIN) $(konto1_MAIN).cc $(LIOPTS)

$(wg-stack_MAIN): $(wg-stack_MAIN).cc $(wg-stack_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(wg-stack_MAIN) $(wg-stack_MAIN).cc $(LIOPTS)

$(stack1_MAIN): $(stack1_MAIN).cc $(stack1_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(stack1_MAIN) $(stack1_MAIN).cc $(LIOPTS)

$(montecarlo1_MAIN): $(montecarlo1_MAIN).cc $(montecarlo1_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(montecarlo1_MAIN) $(montecarlo1_MAIN).cc $(LIOPTS)

$(useintset_MAIN): $(useintset_MAIN).cc $(useintset_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(useintset_MAIN) $(useintset_MAIN).cc $(LIOPTS)

$(Konto_MAIN): $(Konto_MAIN).cc $(Konto_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(Konto_MAIN) $(Konto_MAIN).cc $(LIOPTS)

$(MonteCarlo_MAIN): $(MonteCarlo_MAIN).cc $(MonteCarlo_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(MonteCarlo_MAIN) $(MonteCarlo_MAIN).cc $(LIOPTS)

$(Inkrementierer_MAIN): $(Inkrementierer_MAIN).cc $(Inkrementierer_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(Inkrementierer_MAIN) $(Inkrementierer_MAIN).cc $(LIOPTS)

$(UseRational_MAIN): $(UseRational_MAIN).cc $(UseRational_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(UseRational_MAIN) $(UseRational_MAIN).cc $(LIOPTS)

$(Turingmaschine_MAIN): $(Turingmaschine_MAIN).cc $(Turingmaschine_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(Turingmaschine_MAIN) $(Turingmaschine_MAIN).cc $(LIOPTS)

$(UseSimpleFloatArray_MAIN): $(UseSimpleFloatArray_MAIN).cc $(UseSimpleFloatArray_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(UseSimpleFloatArray_MAIN) $(UseSimpleFloatArray_MAIN).cc $(LIOPTS)

$(UseRationalOutput_MAIN): $(UseRationalOutput_MAIN).cc $(UseRationalOutput_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(UseRationalOutput_MAIN) $(UseRationalOutput_MAIN).cc $(LIOPTS)

$(UsePolynomial_MAIN): $(UsePolynomial_MAIN).cc $(UsePolynomial_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(UsePolynomial_MAIN) $(UsePolynomial_MAIN).cc $(LIOPTS)

$(UseCheckedSimpleFloatArray_MAIN): $(UseCheckedSimpleFloatArray_MAIN).cc $(UseCheckedSimpleFloatArray_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(UseCheckedSimpleFloatArray_MAIN) $(UseCheckedSimpleFloatArray_MAIN).cc $(LIOPTS)

$(shape_MAIN): $(shape_MAIN).cc $(shape_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(shape_MAIN) $(shape_MAIN).cc $(LIOPTS)

$(Funktor_MAIN): $(Funktor_MAIN).cc $(Funktor_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(Funktor_MAIN) $(Funktor_MAIN).cc $(LIOPTS)

$(UseFloatArray_MAIN): $(UseFloatArray_MAIN).cc $(UseFloatArray_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(UseFloatArray_MAIN) $(UseFloatArray_MAIN).cc $(LIOPTS)

$(Funktional-statisch_MAIN): $(Funktional-statisch_MAIN).cc $(Funktional-statisch_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(Funktional-statisch_MAIN) $(Funktional-statisch_MAIN).cc $(LIOPTS)

$(UseSimpleArray_MAIN): $(UseSimpleArray_MAIN).cc $(UseSimpleArray_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(UseSimpleArray_MAIN) $(UseSimpleArray_MAIN).cc $(LIOPTS)

$(PtrTest_MAIN): $(PtrTest_MAIN).cc $(PtrTest_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(PtrTest_MAIN) $(PtrTest_MAIN).cc $(LIOPTS)

$(UseBubblesort_MAIN): $(UseBubblesort_MAIN).cc $(UseBubblesort_INCLUDES) Makefile
	$(CC) $(OPTOPTS) -o $(UseBubblesort_MAIN) $(UseBubblesort_MAIN).cc $(LIOPTS)

$(UseListe_MAIN): $(UseListe_MAIN).cc $(UseListe_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(UseListe_MAIN) $(UseListe_MAIN).cc $(LIOPTS)

$(UseDLL_MAIN): $(UseDLL_MAIN).cc $(UseDLL_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(UseDLL_MAIN) $(UseDLL_MAIN).cc $(LIOPTS)

$(UseBoth_MAIN): $(UseBoth_MAIN).cc $(UseBoth_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(UseBoth_MAIN) $(UseBoth_MAIN).cc $(LIOPTS)

$(UseStack_MAIN): $(UseStack_MAIN).cc $(UseStack_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(UseStack_MAIN) $(UseStack_MAIN).cc $(LIOPTS)

$(UseQueueSTL_MAIN): $(UseQueueSTL_MAIN).cc $(UseQueueSTL_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(UseQueueSTL_MAIN) $(UseQueueSTL_MAIN).cc $(LIOPTS)

$(HuffmanSTL_MAIN): $(HuffmanSTL_MAIN).cc $(HuffmanSTL_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(HuffmanSTL_MAIN) $(HuffmanSTL_MAIN).cc $(LIOPTS)

$(UseHeap_MAIN): $(UseHeap_MAIN).cc $(UseHeap_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(UseHeap_MAIN) $(UseHeap_MAIN).cc $(LIOPTS)

$(UseSort_MAIN): $(UseSort_MAIN).cc $(UseSort_INCLUDES) Makefile
	$(CC) $(OPTOPTS) -o $(UseSort_MAIN) $(UseSort_MAIN).cc $(LIOPTS)

$(ABTree_MAIN): $(ABTree_MAIN).cc $(ABTree_INCLUDES) Makefile
	$(CC) $(OPTOPTS) -o $(ABTree_MAIN) $(ABTree_MAIN).cc $(LIOPTS)

$(LSBeispiel_MAIN): $(LSBeispiel_MAIN).cc $(LSBeispiel_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(LSBeispiel_MAIN) $(LSBeispiel_MAIN).cc $(LIOPTS)

$(AdderBeispiel_MAIN): $(AdderBeispiel_MAIN).cc $(AdderBeispiel_INCLUDES) Makefile
	$(CC) $(CCOPTS) -o $(AdderBeispiel_MAIN) $(AdderBeispiel_MAIN).cc $(LIOPTS)

clean:
	rm -f $(EXECUTABLES)

