name: xournalpp-tools
on: push
jobs:
  xopp-to-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - run: sudo apt install xournalpp
      - run: xournalpp -p contact_geometry/definitions.pdf contact_geometry/definitions.xopp
